[functions]
  node_bundler = "esbuild"
  directory = "functions"

[[redirects]]
  from = "/io/put/*"
  to = "/.netlify/functions/put_addnew"
  status = 200
  method = "PUT"

[[redirects]]
  from = "/io/post-edit/*"
  to = "/.netlify/functions/post_edit"
  status = 200
  method = "POST"

[[redirects]]
  from = "/io/post-search/*"
  to = "/.netlify/functions/post_search"
  status = 200
  method = "POST"

[[redirects]]
  from = "/io/delete/*"
  to = "/.netlify/functions/delete_id"
  status = 200
  method = "DELETE"

[[redirects]]
  from = "/io/get/*"
  to = "/.netlify/functions/get_request"
  status = 200
  method = "GET"

[context.dev.environment]
  RECAPTCHA_SECRET_KEY	= "6LeFwS4iAAAAAOxxjNx4lst6J9o4qz2vKr8qZzBT"
  
[dev]
  port = 6363
  autoLaunch = false